kind: pipeline
name: default armhf

platform:
  arch: arm

steps:
- name: Print environ
  image: debian:buster
  commands:
  - printenv
  - uname -a
  - uname -r
  - uname -m
  - cat /proc/cpuinfo

---

kind: pipeline
name: default arm64

platform:
  arch: arm64

steps:
- name: Print environ
  image: debian:buster
  commands:
  - printenv
  - uname -a
  - uname -r
  - uname -m
  - cat /proc/cpuinfo
