kind: pipeline
name: default

platform:
  arch: amd64

steps:
- name: registry
  image: registry:2
  detach: true
  pull: if-not-exists

- name: Print environ
  image: debian:buster
  pull: if-not-exists
  commands:
  - printenv
  - uname -a
  - uname -r

- name: dind
  image: plugins/docker
  commands:
    - docker -v

- name: Docker build
  image: plugins/docker
  settings:
    repo: registry:5000/testing
    registry: registry:5000
    insecure: true

- name: test image
  image: registry:5000/testing
  commands:
    - uname -a

network_mode: overlay