kind: pipeline
name: default

platform:
  arch: amd64

steps:
- name: registry.local
  image: registry:2
  detach: true
  pull: if-not-exists

- name: Print environ
  image: debian:buster
  pull: if-not-exists
  commands:
  - printenv
  - uname -a
  - uname -r

- name: Docker build
  image: plugins/docker
  settings:
    repo: registry.local:5000/testing
    registry: registry.local:5000
    insecure: true

- name: test image
  image: weberlars/diuid
  commands:
    - uname -a
    - docker -v
    - docker pull eryaf/mk-cross-builder:amd64_10