kind: pipeline
name: default armhf

platform:
  arch: arm

steps:
- name: registry
  image: registry:2
  detach: true
  pull: if-not-exists

- name: Print environ
  image: debian:buster
  pull: if-not-exists
  commands:
  - printenv
  - uname -a
  - uname -r
  - uname -m
  - cat /proc/cpuinfo

network_mode: overlay
---

kind: pipeline
name: default arm64

platform:
  arch: arm64

steps:
- name: registry
  image: registry:2
  detach: true
  pull: if-not-exists

- name: Print environ
  image: debian:buster
  pull: if-not-exists
  commands:
  - printenv
  - uname -a
  - uname -r
  - uname -m
  - cat /proc/cpuinfo

network_mode: overlay