kind: pipeline
name: default

platform:
  arch: amd64

steps:
- name: redis
  image: redis
  detach: true
  pull: if-not-exists

- name: machinekit-registry
  image: registry:2
  detach: true
  pull: if-not-exists

- name: Print environ
  image: debian:buster
  pull: if-not-exists
  commands:
  - printenv
  - uname -a
  - uname -r

- name: test
  image: redis
  pull: if-not-exists
  commands:
  - sleep 5
  - redis-cli -h redis ping
  - redis-cli -h redis set FOO bar
  - redis-cli -h redis get FOO

- name: test2
  image: eryaf/mk-cross-builder:armhf_8
  pull: if-not-exists
  commands:
  - sleep 5
  - apt-get update

- name: Docker maybe
  image: plugins/docker
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - docker -v
  - docker pull debian:buster

---
kind: pipeline
name: default2

steps:
- name: test
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 5 # give docker enough time to start
  - docker ps -a

services:
- name: docker
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}