kind: pipeline
name: default

platform:
  arch: arm64

steps:
- name: redis
  image: redis
  detach: true
  pull: if-not-exists

- name: machinekit-registry
  image: registry:2
  detach: true
  pull: if-not-exists

- name: Print environ
  image: debian:buster
  pull: if-not-exists
  commands:
  - printenv
  - uname -a
  - uname -r

- name: test
  image: redis
  pull: if-not-exists
  commands:
  - sleep 5
  - redis-cli -h redis ping
  - redis-cli -h redis set FOO bar
  - redis-cli -h redis get FOO
